language: python

install:
  - pip install mkdocs-material mkdocs-redirects pymdown-extensions
  - pip install -r requirements.txt

script:
  - mkdocs build --clean --strict
  cd docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs/build
  on:
    branch: master