language: python

install:
  - pip install -r docs/requirements.txt
  - pip install -r requirements.txt

script:
  - python skidtools --init
  - python -m unittest discover
  - mkdocs build --clean --strict
  

deploy:
  provider: pages
  allow_empty_commit: true
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: site

deploy:
  provider: pypi
  username: Abdos
  password: $PIPY_PW
  edge: true # opt in to dpl v2

  on:
    branch: master