# Project information
site_name: Skidtools Docs
site_url: https://clast.dev
site_author: Abdos
site_description: >-
  A collection of utilities and tools to rapidly develop CLI programs. It aims to get rid of boilerplate and aid skiddies.
# Repository
repo_name: Abd0s/skidtools
repo_url: https://github.com/Abd0s/skidtools
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 Clast

# Configuration
theme:
  name: material
  features:
    - instant
  #  - tabs

  language: en
  palette:
    primary: purple
    accent: purple
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.svg
  favicon: assets/logo.png

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Abd0s
    - icon: fontawesome/solid/flask
      link: https://labs.clast.dev
    - icon: fontawesome/solid/home
      link: https://clast.dev

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - meta

  # PyMdown
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

